### ISSUE TITLE
trimmomatic appears as not installed

### ISSUE THREAD

**Issue by drelo** [faircloth-lab/illumiprocessor#10]
I got this error while trying to clean the Alligator sequences provided in the train data. 

```
Traceback (most recent call last):
  File "/home/andrelo/miniconda2/bin/illumiprocessor", line 17, in <module>
    sys.exit(main())
  File "/home/andrelo/miniconda2/lib/python2.7/site-packages/illumiprocessor/cli/main.py", line 131, in main
    main(args)
  File "/home/andrelo/miniconda2/lib/python2.7/site-packages/illumiprocessor/main.py", line 22, in main
    core.check_dependencies(args)
  File "/home/andrelo/miniconda2/lib/python2.7/site-packages/illumiprocessor/core.py", line 259, in check_dependencies
    java.test_trimmomatic(args.trimmomatic)
  File "/home/andrelo/miniconda2/lib/python2.7/site-packages/illumiprocessor/core.py", line 252, in test_trimmomatic
    "Trimmomatic does not appear to be installed"
```

I got this error even when I installed phyluce days ago, I also did 

> conda install illumiprocessor

How can I get a better diagnose and try to fix this? Thanks

**Comment by drelo** [comment]
I also installed illuminoprocessor via the script contained in the source, although I don't understand how to install Trimmomatic in a Linux machine (since I only see the binary and can't compile from source).
