### ISSUE TITLE
create_new_dirs : self.end_name fails when samples named X01-X100 or X1-X10. 

### ISSUE THREAD

**Issue by MikeWLloyd** [faircloth-lab/illumiprocessor#11]
When raw reads are named in the follow way:
 
```
X01
..
X10
..
X100

OR 

X1
..
X10
```

The symlinks for the `create_new_dirs` function in `Core.py` throws the following error: 

```
[lloydm@login-30-1 raw-reads]$ cat illumi.log                       
...log info omitted...
Traceback (most recent call last):
  File "/share/apps/bioinformatics/phyluce_tg/anaconda2/bin/illumiprocessor", line 17, in <module>
    sys.exit(main())
  File "/share/apps/bioinformatics/phyluce_tg/anaconda2/lib/python2.7/site-packages/illumiprocessor/cli/main.py", line 161, in main
    main(args)
  File "/share/apps/bioinformatics/phyluce_tg/anaconda2/lib/python2.7/site-packages/illumiprocessor/main.py", line 36, in main
    core.create_new_dirs(reads)
  File "/share/apps/bioinformatics/phyluce_tg/anaconda2/lib/python2.7/site-packages/illumiprocessor/core.py", line 376, in create_new_dirs
    os.symlink(reads, new_file)
OSError: [Errno 17] File exists
```

In the last directory `illumiprocessor` was working on: 
```
[lloydm@login-30-1 raw-reads]$ pwd
/pool/genomics/phyluce_ouput/clean_fastq/Ocy010/raw-reads

[lloydm@login-30-1 raw-reads]$ la
total 4.0K
lrwxrwxrwx 1 lloydm lloydm 92 Oct 25 09:22 Ocy010-READ1.fastq.gz -> /pool/genomics/raw_reads/14578X100_170915_D00294_0341_ACBMGUANXX_4_1.txt.gz
```
Somehow `sample.end_name` is not catching the difference between X10 & X100 or X1 & X10, and the symlink is trying to link X100 to X10 or X10 to X1, and failing. The workaround is to rename the read files, but could the script catch these cases?

**Comment by MikeWLloyd** [comment]
Sorry, forgot I had this open. Yes, I had the incorrect regex. I was missing the "{}" in the statement. Once that was added, problem solved.
