### ISSUE TITLE
Illumiprocessor error

### ISSUE THREAD

**Issue by ClayAssis** [faircloth-lab/illumiprocessor#13]
Hello

I'm having trouble running the illumiprocessor. When I run the line " illumiprocessor --input ~/Documents/RAPID_GENOMICS/fastq --output ~/Documents/RAPID_GENOMICS/fastq/results --config ~/Documents/RAPID_GENOMICS/illumiprocessor.conf --trimmomatic /home/claydson/miniconda2/jar/trimmomatic.jar --cores 15 --r1-pattern _r1 --r2-pattern _r2

I'm encountering the following error:

Traceback (most recent call last):
  File "/home/claydson/miniconda2/bin/illumiprocessor", line 17, in <module>
    sys.exit(main())
  File "/home/claydson/miniconda2/lib/python2.7/site-packages/illumiprocessor/cli/main.py", line 121, in main
    main(args)
  File "/home/claydson/miniconda2/lib/python2.7/site-packages/illumiprocessor/main.py", line 22, in main
    core.check_dependencies(args)
  File "/home/claydson/miniconda2/lib/python2.7/site-packages/illumiprocessor/core.py", line 241, in check_dependencies
    java.test_trimmomatic(args.trimmomatic)
  File "/home/claydson/miniconda2/lib/python2.7/site-packages/illumiprocessor/core.py", line 229, in test_trimmomatic
    stderr=subprocess.PIPE
  File "/home/claydson/miniconda2/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/home/claydson/miniconda2/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

I missing something?

Thanks

**Comment by ClayAssis** [comment]
Fixed!

**Comment by genevalab** [comment]
A student is having the same issue. Can you provide some detail on how you fixed this error?
