### ISSUE TITLE
illumiprocessor OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by yksun** [faircloth-lab/illumiprocessor#16]
Run illumiprocessor having issues. Wondering if any idea for this? Thanks

illumiprocessor --input raw_data_Artibeus_fraterculus --output clean_fastq --config Illumiprocessor_AF.conf --r1-pattern _1.fq.gz --r2-pattern _2.fq.gz

[WARNING] Output directory exists, REMOVE [Y/n]? Y

2020-12-01 17:26:47,598 - illumiprocessor - INFO - ==================== Starting illumiprocessor ===================

2020-12-01 17:26:47,598 - illumiprocessor - INFO - Version: 2.0.9

2020-12-01 17:26:47,598 - illumiprocessor - INFO - Argument --config: Illumiprocessor_AF.conf

2020-12-01 17:26:47,598 - illumiprocessor - INFO - Argument --cores: 1

2020-12-01 17:26:47,599 - illumiprocessor - INFO - Argument --input: /home/ncortes/Novogene_Data/raw_data_Artibeus_fraterculus

2020-12-01 17:26:47,599 - illumiprocessor - INFO - Argument --log_path: None

2020-12-01 17:26:47,599 - illumiprocessor - INFO - Argument --min_len: 40

2020-12-01 17:26:47,599 - illumiprocessor - INFO - Argument --no_merge: False

2020-12-01 17:26:47,599 - illumiprocessor - INFO - Argument --output: /home/ncortes/Novogene_Data/clean_fastq

2020-12-01 17:26:47,599 - illumiprocessor - INFO - Argument --phred: phred33

2020-12-01 17:26:47,599 - illumiprocessor - INFO - Argument --r1_pattern: _1.fq.gz

2020-12-01 17:26:47,599 - illumiprocessor - INFO - Argument --r2_pattern: _2.fq.gz

2020-12-01 17:26:47,600 - illumiprocessor - INFO - Argument --se: False

2020-12-01 17:26:47,600 - illumiprocessor - INFO - Argument --trimmomatic: /home/ncortes/anaconda/envs/phyluce/bin/trimmomatic

2020-12-01 17:26:47,600 - illumiprocessor - INFO - Argument --verbosity: INFO

2020-12-01 17:26:47,666 - illumiprocessor - INFO - Trimming samples with Trimmomatic

Running...........................Traceback (most recent call last):

  File "/home/ncortes/anaconda/envs/phyluce/bin/illumiprocessor", line 17, in <module>

    sys.exit(main())

  File "/home/ncortes/anaconda/envs/phyluce/lib/python2.7/site-packages/illumiprocessor/cli/main.py", line 121, in main

    main(args)

  File "/home/ncortes/anaconda/envs/phyluce/lib/python2.7/site-packages/illumiprocessor/main.py", line 47, in main

    map(core.runner, work)

  File "/home/ncortes/anaconda/envs/phyluce/lib/python2.7/site-packages/illumiprocessor/core.py", line 317, in runner

    trimmomatic_merger(sample)

  File "/home/ncortes/anaconda/envs/phyluce/lib/python2.7/site-packages/illumiprocessor/core.py", line 304, in trimmomatic_merger

    os.rename(singles[0], new_pth)

OSError: [Errno 2] No such file or directory

**Comment by brantfaircloth** [comment]
The patterns you are using for `--r1-pattern` and `--r2-pattern` are not correct.  These need to be regular expressions to match your read file names, but it does not appear that they are regular expressions, at all.
