### ISSUE TITLE
Error in _get_tag_data self.i5s = self.revcomp(tags[self.i5])

### ISSUE THREAD

**Issue by jbernst** [faircloth-lab/illumiprocessor#17]
Hello,

I am currently trying to use Illumiprocessor (phyluce v 1.7.1, miniconda3, python v 3.6.13) to clean some genomic data (a dataset that contains primarily UCEs, but also AHE and nuclear loci). I am running this on 6 samples to test it out and  have the following as my `illumiprocessor.conf` file:
```
# this is the section where you list the adapters you used.  the asterisk
# will be replaced with the appropriate index for the sample.
[adapters]
i7:AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC*ATCTCGTATGCCGTCTTCTGCTT
i5:AATGATACGGCGACCACCGAGATCTACAC*ACACTCTTTCCCTACACGACGCTCTTCCGATCT

# this is the list of indexes we used
[tag sequences]
6112-JK-12_1-1:GAGATTCC
6112-JK-12_1-2:AGCAGTTG
6112-JK-12_2-1:CACTTCGA
6112-JK-12_2-2:GGTTCGAA
6112-JK-12_3-1:GACAGTGC
6112-JK-12_3-2:ATAGCAAG
6112-JK-18_001-1:AACAGTTG
6112-JK-18_001-2:TATAGCCT
6112-JK-18_002-1:AACACATA
6112-JK-18_002-2:CTGTAGCC
6112-JK-18_003-1:TTCAAGAA
6112-JK-18_003-2:AGCCATGC

# this is how each index maps to each set of reads
[tag map]
6112-JK-12_1_S1:6112-JK-12_1-1,6112-JK-12_1-2
6112-JK-12_2_S1:6112-JK-12_2-1,6112-JK-12_2-2
6112-JK-12_3_S1:6112-JK-12_3-1,6112-JK-12_3-2
6112-JK-18_001_S1:6112-JK-18_001-1,6112-JK-18_001-2
6112-JK-18_002_S1:6112-JK-18_002-1,6112-JK-18_002-2
6112-JK-18_003_S1:6112-JK-18_003-1,6112-JK-18_003-2

# we want to rename our read files something a bit more nice - so we will
# rename Alligator_mississippiensis_GGAGCTATGG to alligator_mississippiensis
[names]
6112-JK-12_1_S1:Bgas_ABCD_XXXXX1
6112-JK-12_2_S1:Bgas_ABCD_XXXXX2
6112-JK-12_3_S1:Bgas_ABCD_XXXXX3
6112-JK-18_001_S1:Bhyd_ABCD_XXXXX1
6112-JK-18_002_S1:Balb_ABCD_XXXXX1
6112-JK-18_003_S1:Cvio_ABCD_XXXXX1
```

When I run illumiprocessor using:
```
illumiprocessor --input ./TEST_raw-reads \
--output ./clean_fastq_family \
--config illumiprocessor_family_TEST-run.conf \
--cores 16 \
--r1-pattern _L005_R1_001 \
--r2-pattern _L005_R2_001
```

I get the following error:
```
Traceback (most recent call last):
  File "/home/jmb689/miniconda3/envs/phyluce-1.7.1/bin/illumiprocessor", line 17, in <module>
    sys.exit(main())
  File "/home/jmb689/miniconda3/envs/phyluce-1.7.1/lib/python3.6/site-packages/illumiprocessor/cli/main.py", line 114, in main
    main(args)
  File "/home/jmb689/miniconda3/envs/phyluce-1.7.1/lib/python3.6/site-packages/illumiprocessor/main.py", line 34, in main
    reads.append(core.SequenceData(args, conf, start_name, end_name))
  File "/home/jmb689/miniconda3/envs/phyluce-1.7.1/lib/python3.6/site-packages/illumiprocessor/core.py", line 86, in __init__
    self._get_tag_data(conf)
  File "/home/jmb689/miniconda3/envs/phyluce-1.7.1/lib/python3.6/site-packages/illumiprocessor/core.py", line 127, in _get_tag_data
    self.i5s = self.revcomp(tags[self.i5])
KeyError: None
```

The files that are in my `TEST_raw-reads` directory are:
```
6112-JK-12_1_S1_L005_R1_001.fastq.gz
6112-JK-12_1_S1_L005_R2_001.fastq.gz
6112-JK-12_2_S1_L005_R1_001.fastq.gz
6112-JK-12_2_S1_L005_R2_001.fastq.gz
6112-JK-12_3_S1_L005_R1_001.fastq.gz
6112-JK-12_3_S1_L005_R2_001.fastq.gz
6112-JK-18_001_S1_L005_R1_001.fastq.gz
6112-JK-18_001_S1_L005_R2_001.fastq.gz
6112-JK-18_002_S1_L005_R1_001.fastq.gz
6112-JK-18_002_S1_L005_R2_001.fastq.gz
6112-JK-18_003_S1_L005_R1_001.fastq.gz
6112-JK-18_003_S1_L005_R2_001.fastq.gz
```

Did I format something wrong with the adapters? 

Any help is appreciated; thank you!

**Comment by jbernst** [comment]
**Solved:**
The error was that I did not add 'i7' or 'i5' to the beginning of the tag sequences. My new `[tag sequence]` section now reads:

```
[tag sequences]
i7-6112-JK-12_1-1:GAGATTCC
i5-6112-JK-12_1-2:AGCAGTTG
i7-6112-JK-12_2-1:CACTTCGA
i5-6112-JK-12_2-2:GGTTCGAA
i7-6112-JK-12_3-1:GACAGTGC
i5-6112-JK-12_3-2:ATAGCAAG
i7-6112-JK-18_001-1:AACAGTTG
i5-6112-JK-18_001-2:TATAGCCT
i7-6112-JK-18_002-1:AACACATA
i5-6112-JK-18_002-2:CTGTAGCC
i7-6112-JK-18_003-1:TTCAAGAA
i5-6112-JK-18_003-2:AGCCATGC
```

and it is running.
