### ISSUE TITLE
Problem with the ConfigParser

### ISSUE THREAD

**Issue by lsbarrientos50** [faircloth-lab/illumiprocessor#5]
I have problems with the ConfigParser.py it could't find the section "names" in my config file. I double check that all the names will be ok and the path is ok. I try to find if the ConfigParser.py have some problem but I can't find one. I checked if is a problem in the installation of illumiprocessor or the trimmomatic or java and they look ok. I try I reinstall everything and the problem still be there. 

![captura_de_pantalla_2_16_15 _1_55_pm](https://cloud.githubusercontent.com/assets/10567184/6642336/e210c238-c971-11e4-9093-0094d791fabc.jpeg)

**Comment by akijarl** [comment]
I'm having this exact same problem now. Was there ever a clear solution to this?

**Comment by GideonPisanty** [comment]
Same problem... if anyone has a solution please post it here. Thanks.

**Comment by GideonPisanty** [comment]
I have tried several different versions of the config file and none worked. This is the latest one:

[adapters]
i7:GATCGGAAGAGCACACGTCTGAACTCCAGTCAC*ATCTCGTATGCCGTCTTCTGCTTG
i5:AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT*GTGTAGATCTCGGTGGTCGCCGTATCATT
[tag sequences]
i7-112_06:CCGGAATT
i5-19_F:TGGCTCTT
[tag map]
aegyptiaca_S34:i7-112_06,i5-19_F
[names]
aegyptiaca_S34:aegyptiaca


![image](https://user-images.githubusercontent.com/35965642/35581406-adc946da-05b9-11e8-8d3d-359a1cc38868.png)

**Comment by GideonPisanty** [comment]
I have tried several different versions of the config file and none worked. This is the latest one.
Thanks 
Gideon Pisanty
Post-doctoral fellowCanadian National Collection of Insects (CNC)/Collection nationale canadienne d'insects (CNC)Agriculture and Agri-Food Canada/Agriculture et Agroalimentaire Canada960 Carling Avenue, Ottawa, Ontario, CANADA K1A 0C6Telephone/Téléphone: 613-759-6369Facsimile/Télécopieur: 613-759-1701gidpisa79@yahoo.comgideon.pisanty@canada.ca

**Comment by brantfaircloth** [comment]
The following config file appears to work fine for me:

```
[adapters]
i7:GATCGGAAGAGCACACGTCTGAACTCCAGTCAC*ATCTCGTATGCCGTCTTCTGCTTG
i5:AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT*GTGTAGATCTCGGTGGTCGCCGTATCATT

[tag sequences]
i7-112_06:CCGGAATT
i5-19_F:TGGCTCTT

[tag map]
aegyptiaca_S34:i7-112_06,i5-19_F

[names]
aegyptiaca_S34:aegyptiaca
```

when the input are two files in a directory named `test`, as below:

```
aegyptiaca_S34_T3_R1_001.fastq.gz
aegyptiaca_S34_T3_R2_001.fastq.gz
```

These are not your data, but two files made to look like your data.  I formed the names so they would be like what `illumiprocessor` expects.  The tree of the input and output folders looks like this:

```
.
├── test
│   ├── aegyptiaca_S34_T3_R1_001.fastq.gz
│   └── aegyptiaca_S34_T3_R2_001.fastq.gz
├── clean
│   └── aegyptiaca
│       ├── adapters.fasta
│       ├── raw-reads
│       │   ├── aegyptiaca-READ1.fastq.gz -> /home/bcf/tmp/test/test/aegyptiaca_S34_T3_R1_001.fastq.gz
│       │   └── aegyptiaca-READ2.fastq.gz -> /home/bcf/tmp/test/test/aegyptiaca_S34_T3_R2_001.fastq.gz
│       ├── split-adapter-quality-trimmed
│       │   ├── aegyptiaca-READ1.fastq.gz
│       │   ├── aegyptiaca-READ2.fastq.gz
│       │   └── aegyptiaca-READ-singleton.fastq.gz
│       └── stats
│           └── aegyptiaca-adapter-contam.txt
├── illumiprocessor.log
└── test.conf
```

**Comment by GideonPisanty** [comment]
Thanks for the answer. For now, I bypassed the problem by running trimmomatic directly. Haven't yet solved this issue.

**Comment by GideonPisanty** [comment]
The problem seems to be solved by including the name of the config file in the "--config" line of the command. Thanks to my colleague Jackson Eyres for solving this.

However, now that it is solved, I have the other issue with the read names, frequently encountered by other users here: 

 "errors in your conf file.".format(self.start_name))
IOError: There is a problem with the read names for morelia-viridis1_GCCTTCA. Ensure you do not have spelling/capitalization errors in your conf file."

I have tried all the solutions mentioned in the threads here and none worked for me.

**Comment by GideonPisanty** [comment]
Thanks.

**Comment by GideonPisanty** [comment]
Now it's working, not sure why. I might have mixed underlines with hyphens in the species names.

**Comment by zhangpizhu** [comment]
I also have a problem like this, I don't know what does means. Is there some error with my config file? if anyone konw how to slove this problem，  
please post it here.thanks
 
my config file as below:

[adapters]
i7:GATCGGAAGAGCACACGTCTGAACTCCAGTCAC*ATCTCGTATGCCGTCTTCTGCTTG
i5:AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT*GTGTAGATCTCGGTGGTCGCCGTATCATT

[tag sequences]
i7-7893:GAATCTGT
i5-7893:ATAGCGAC

[tag map]
sl337893:i7-7893,i5-7893

[names]
sl337893:sl337893

The names of input file as below:

sl337893_T1_R1_7893.fastq.gz
sl337893_T1_R2_7893.fastq.gz
![2018-11-12 21_32_41____________](https://user-images.githubusercontent.com/43691535/48415407-47bdf500-e788-11e8-89b0-b76e0dc57c67.png)

**Comment by brantfaircloth** [comment]
See above.  You'll likely need to adjust either your config file or the regular expression to deal with your file names.

**Comment by zhangpizhu** [comment]
I've dealt with my problems. Thank you very much.

**Comment by mchj74** [comment]
Hi Brant, I am having issues with config file getting the following when try to run illumiprocessor: 

for a single-indexed library, i7 is my index primer sequence and i5 is the NEBNEXT universal primer sequence. Two files  of 
BRF27_POM134_S27_R1_001.fastq.gz   and 
BRF27_POM134_S27_R2_001.fastq.gz
are inside a folder POM134 

The script I am using is:
module load phyluce/1.6.8
module load illumiprocessor/2.0.9
illumiprocessor --input POM134 --output clean --config illumiprocessor.conf --cores 4 --trimmomatic ${TRIMMOMATIC_HOME}/bin/trimmomatic

The config file is as below:

[adapters]
i7:CAAGCAGAAGACGGCATACGAGAT*GTGACTGGAGTTCAGACGTGTGCTCTTCCGATCT
i5:AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT

[tag sequences]
i7-P1-A1:TTACCGAC

[tag map]
BRF27_POM134_S27:i7-P1-A1

[names]
BRF27_POM134_S27:C.sp

I am getting this error many times:
   "errors in your conf file.".format(self.start_name))
IOError: There is a problem with the read names for BRF27_POM134_S27. Ensure you do not have spelling/capitalization errors in your conf file.
Can you help how I can fix it?

**Comment by brantfaircloth** [comment]
It looks like your reads are named in a way that is not expected by phyluce.  This means that you need to change the regular expression used to match the read data given the read names.  The following should do it, although I have not tested:
```
--r1_pattern "{}_(R1)_\d+.fastq(?:.gz)*"
--r2_pattern "{}_(R2)_\d+.fastq(?:.gz)*"
```
Also, when you rename your reads in the `[names]` section, you need to use something that does not contain most symbols (underscore "_" is ok). For example:
```
[names]
BRF27_POM134_S27:C_sp
```

**Comment by mchj74** [comment]
Not sorted

**Comment by nayeligarcia9716-crypto** [comment]
I’m currently running into the same problem. Can you see a formatting error in my file, or could you clarify the usage of [names]?  

The error message is  

Traceback (most recent call last): File "/home1/10879/ngarc1627/miniconda3/envs/illumiprocessor/lib/python3.6/configparser.py", line 846, in items d.update(self._sections[section]) KeyError: 'names' 

During handling of the above exception, another exception occurred: 

Traceback (most recent call last): File "/home1/10879/ngarc1627/miniconda3/envs/illumiprocessor/bin/illumiprocessor", line 17, in <module> sys.exit(main())  ile "/home1/10879/ngarc1627/miniconda3/envs/illumiprocessor/lib/python3.6/site- packages/illumiprocessor/cli/main.py", line 114, in main  

main(args)  File "/home1/10879/ngarc1627/miniconda3/envs/illumiprocessor/lib/python3.6/site-packages/illumiprocessor/main.py", line 33, in main for start_name, end_name in conf.items("names"): File "/home1/10879/ngarc1627/miniconda3/envs/illumiprocessor/lib/python3.6/configparser.py", line 849, in items raise NoSectionError(section) configparser.NoSectionError: No section: 'names' 


Update: We resolved the issue as we discovered it was an error with finding the .conf file and not in the [names].  If anyone else has this issue, double check for an issue in your paths and file names.
